### ISSUE TITLE
Создать анимацию для капель воды в хэдере лендинга endlesswatering

### ISSUE THREAD

**Issue by alexkovaluoff** [TAKTIL-tech/endlesswatering.org#23]
Создать анимацию для капель воды в хэдере лендинга

![image](https://user-images.githubusercontent.com/83351704/127648531-e521f5b6-8ba7-4e24-a8ff-93f0dd431615.png)

Необходимо добавить эффект капающих из бутылки сверху вниз капель воды. Поле для анимации капель от бутылки до нижнего края элемента 113рх

**Comment by annamaksimik** [comment]
[task#23.svg.zip](https://github.com/TAKTIL-tech/endlesswatering.org/files/6908188/task.23.svg.zip)

**Comment by annamaksimik** [comment]
[task#23.zip](https://github.com/TAKTIL-tech/endlesswatering.org/files/6908318/task.23.zip)
